# @see https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: Example Action 1
description: Example action 1 description

inputs:
  input_1: { description: input 1 description }
  input_2: { description: input 2 description }

runs:
  using: composite
  steps:
    - name: Dump GitHub context
      run: echo "$GITHUB_CONTEXT"
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Run ls
      run: ls -al
      shell: bash
    - name: Run script.sh
      run: script.sh
      shell: bash
